### ISSUE TITLE
Distribute mode and sharding

### ISSUE THREAD

**Issue by siscia** [RedisLabsModules/secondary#1]
Hi,

I am looking with a lot of interest this project.

Especially I am wondering what are your design choice with the respect of distribute mode and sharding.

For sure you can move indexes between different machines and this looks perfectly good. 

What happens when inside an index you have a key that reside on a different machine?
Have you already think about the issue? What kind of trade off are you considering?

Cheers,
Simone

**Comment by dvirsky** [comment]
Hi @siscia. 
This is indeed an interesting topic. 
There are two main approaches to it - Global indexes vs. local indexes. 
Global indexes means that you separate the indexing from where the data is saved. As you can see in the API, the indexes can be used as a raw data type and not track changes automatically. 
In this case, you have a proxy or a coordinator that takes a query, and first queries the index, which is stored on as little shards as possible (1 would be ideal). then it gets ids from the index, and calls the relevant shards.
This approach requires a lot of complex logic on the coordinator, especially when updating during writes.

The second, "simpler" yet less scalable approach is called local indexing. In this approach we have an index on every shard, indexing the objects in this shard. when a query arrives, we need to send the query to ALL shards, then each shard returns its own results, and we aggregate them to one result set. 

This approach is less scalable as you need to talk to all shards constantly, and it's more complicated in case an object gets moved to another shard, and you need to reflect that in the indexes. but OTOH it's way easier to handle since there is very little logic on the coordinator. 

I'm not sure yet which one I'll take, each have their own drawbacks and complications, and will require a lot of work. 

In both cases, a coordinator will be necessary, that will manage queries on the cluster level.

I'm closing the issue as it's not really an issue. but you can continue commenting here if you want to discuss it further.

**Comment by siscia** [comment]
Hi @dvirsky ,

here it is just passed Christmas, I don't know if that means nothing to you, but I would still like to wish the best for you and all your family and closest friends.

A global coordinator -- in the environment of a Redis module -- seems more complex that what I am confident to do with easy. (I hate to write coordinators...)

I am thinking about a slightly different solution, if I could subscribe to change in the redis key space I could easily set for a global index.

Thanks for your input in this discussion,

Best Wishes

Simone

**Comment by dvirsky** [comment]
Thanks, I'm not celebrating Christmas but appreciated, Merry Christmas to you too. 

While your solution would work for indexing, you would still need a coordinator when you run a query, to aggregate the result from all shards. I don't see a design that can bypass it, but if you have an idea, do share it.
